spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cg523l06vmzk.ap-southeast-1.rds.amazonaws.com:5432/capstone
    username: postgres
    password: myfirstproject
  servlet:
    multipart:
      max-file-size: 50MB