spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-2.chpzw3uvtrlc.ap-east-1.rds.amazonaws.com:5432/capstone
    username: postgres
    password: myfirstproject
  servlet:
    multipart:
      max-file-size: 50MB